### ISSUE TITLE
[Bug]: Trying to move the video preview on 0.7.5

### ISSUE THREAD

**Issue by HonzoNebro** [bekriebel/fvtt-module-webrtc_tweaks#8]
This is what happens when you use the "Change position" option
![imagen](https://user-images.githubusercontent.com/5500663/97580039-18473800-19f3-11eb-972c-4dbd9112773f.png)

**Comment by JJBocanegra** [comment]
I'm having similar problems, I can't move it from the right side, and even appears behind the chat sidebar.

**Comment by bekriebel** [comment]
Fixed in v0.5.0
